chore: Reset error count between rows. herpderp
Commit generated by whatthecommit.com

Signed-off-by: Rene Koens <mavy@ninjanerd.eu>

diff --git a/.github/workflows/nix-build.yaml b/.github/workflows/nix-build.yaml
--- a/.github/workflows/nix-build.yaml
+++ b/.github/workflows/nix-build.yaml
@@ -27,30 +27,8 @@ env:
   HOME: /root
 
 jobs:
-  create-runner:
-    if: github.event.pull_request.draft == false
-    name: Create Hetzner Cloud runner
-    runs-on: ubuntu-latest
-    outputs:
-      label: ${{ steps.create-hcloud-runner.outputs.label }}
-      server_id: ${{ steps.create-hcloud-runner.outputs.server_id }}
-    steps:
-      - name: Create runner
-        id: create-hcloud-runner
-        uses: Cyclenerd/hcloud-github-runner@v1
-        with:
-          mode: create
-          github_token: ${{ secrets.GH_PAT }}
-          hcloud_token: ${{ secrets.HETZNER_TOKEN }}
-          server_type: ccx23
-          image: ubuntu-24.04
-          runner_dir: /actions-runner
-          location: hel1
-
   nix-matrix:
-    runs-on: hetzner
-    needs:
-      - create-runner
+    runs-on: [ hetzner, type-ccx23 ]
     outputs:
       matrix: ${{ steps.set-matrix.outputs.matrix }}
     steps:
@@ -78,128 +56,111 @@ jobs:
         run: |
           echo "${{ toJson(steps.set-matrix.outputs.matrix) }}" >> "${GITHUB_STEP_SUMMARY}"
 
-  nix-build:
-    runs-on: hetzner
-    needs: 
-      - create-runner
-      - nix-matrix
-    permissions:
-      contents: read
-      pull-requests: write
-    strategy:
-      fail-fast: true
-      max-parallel: 1
-      matrix: ${{ fromJSON(needs.nix-matrix.outputs.matrix) }}
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
-        with:
-          fetch-depth: 0
+  # nix-build:
+  #   runs-on: hetzner
+  #   needs: 
+  #     - create-runner
+  #     - nix-matrix
+  #   permissions:
+  #     contents: read
+  #     pull-requests: write
+  #   strategy:
+  #     fail-fast: true
+  #     max-parallel: 1
+  #     matrix: ${{ fromJSON(needs.nix-matrix.outputs.matrix) }}
+  #   steps:
+  #     - name: Checkout repository
+  #       uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
+  #       with:
+  #         fetch-depth: 0
 
-      - name: Install nix
-        uses: DeterminateSystems/nix-installer-action@main
-        with:
-          reinstall: true
-          extra-conf: |
-            experimental-features = nix-command flakes
-            extra-platforms = aarch64-linux
+  #     - name: Install nix
+  #       uses: DeterminateSystems/nix-installer-action@main
+  #       with:
+  #         reinstall: true
+  #         extra-conf: |
+  #           experimental-features = nix-command flakes
+  #           extra-platforms = aarch64-linux
 
-      - name: Set up Magic Nix Cache
-        uses: DeterminateSystems/magic-nix-cache-action@v8
+  #     - name: Set up Magic Nix Cache
+  #       uses: DeterminateSystems/magic-nix-cache-action@v8
 
-      - name: Set up Cachix
-        uses: cachix/cachix-action@v15
-        if: ${{ !github.event.pull_request.head.repo.fork }}
-        with:
-          name: mavy
-          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
+  #     - name: Set up Cachix
+  #       uses: cachix/cachix-action@v15
+  #       if: ${{ !github.event.pull_request.head.repo.fork }}
+  #       with:
+  #         name: mavy
+  #         authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
 
-      - name: Install NVD
-        run: nix profile install nixpkgs#nvd
+  #     - name: Install NVD
+  #       run: nix profile install nixpkgs#nvd
 
-      - name: Garbage collect build dependencies
-        run: nix-collect-garbage
+  #     - name: Garbage collect build dependencies
+  #       run: nix-collect-garbage
 
-      - name: Build previous ${{ matrix.host }} system
-        run: |
-          nix build \
-            "github:NNMavy/nix-config#top.${{ matrix.host }}" \
-            -o result-previous \
-            --log-format raw \
-            --fallback \
-            > >(tee stdout.log) 2> >(tee /tmp/nix-build-err.log >&2)
+  #     - name: Build previous ${{ matrix.host }} system
+  #       run: |
+  #         nix build \
+  #           "github:NNMavy/nix-config#top.${{ matrix.host }}" \
+  #           -o result-previous \
+  #           --log-format raw \
+  #           --fallback \
+  #           > >(tee stdout.log) 2> >(tee /tmp/nix-build-err.log >&2)
 
-      - name: Build new ${{ matrix.host }} system
-        run: |
-          set -o pipefail
-          nix build \
-            ".#top.${{ matrix.host }}" \
-            -o result-new \
-            --fallback \
-            --log-format raw \
-             > >(tee stdout.log) 2> >(tee /tmp/nix-build-err.log >&2)
+  #     - name: Build new ${{ matrix.host }} system
+  #       run: |
+  #         set -o pipefail
+  #         nix build \
+  #           ".#top.${{ matrix.host }}" \
+  #           -o result-new \
+  #           --fallback \
+  #           --log-format raw \
+  #            > >(tee stdout.log) 2> >(tee /tmp/nix-build-err.log >&2)
 
-      - name: Output build failure
-        if: failure()
-        run: |
-          env
-          drv=$(grep "For full logs, run" /tmp/nix-build-err.log | grep -oE "/nix/store/.*.drv")
-          if [ -n $drv ]; then
-            nix log $drv
-            echo $drv
-          fi
-          exit 1
+  #     - name: Output build failure
+  #       if: failure()
+  #       run: |
+  #         env
+  #         drv=$(grep "For full logs, run" /tmp/nix-build-err.log | grep -oE "/nix/store/.*.drv")
+  #         if [ -n $drv ]; then
+  #           nix log $drv
+  #           echo $drv
+  #         fi
+  #         exit 1
 
-      - name: Diff profile
-        id: diff
-        run: |
-          delimiter="$(openssl rand -hex 16)"
-          echo "diff<<${delimiter}" >> "${GITHUB_OUTPUT}"
-          nvd --color never diff ./result-previous ./result-new | sed '/<<</d; />>>/d' >> "${GITHUB_OUTPUT}"
-          echo "${delimiter}" >> "${GITHUB_OUTPUT}"
+  #     - name: Diff profile
+  #       id: diff
+  #       run: |
+  #         delimiter="$(openssl rand -hex 16)"
+  #         echo "diff<<${delimiter}" >> "${GITHUB_OUTPUT}"
+  #         nvd --color never diff ./result-previous ./result-new | sed '/<<</d; />>>/d' >> "${GITHUB_OUTPUT}"
+  #         echo "${delimiter}" >> "${GITHUB_OUTPUT}"
 
-      - name: Generate Token
-        uses: actions/create-github-app-token@v1
-        id: app-token
-        with:
-          app-id: ${{ secrets.BOT_APP_ID }}
-          private-key: ${{ secrets.BOT_APP_PRIVATE_KEY }}
+  #     - name: Generate Token
+  #       uses: actions/create-github-app-token@v1
+  #       id: app-token
+  #       with:
+  #         app-id: ${{ secrets.BOT_APP_ID }}
+  #         private-key: ${{ secrets.BOT_APP_PRIVATE_KEY }}
 
-      - name: Comment report in pr
-        uses: marocchino/sticky-pull-request-comment@v2
-        with:
-          GITHUB_TOKEN: "${{ steps.app-token.outputs.token }}"
-          header: ".#top.${{ matrix.host }}"
-          message: |
-            ### Report for `${{ matrix.host }}`
+  #     - name: Comment report in pr
+  #       uses: marocchino/sticky-pull-request-comment@v2
+  #       with:
+  #         GITHUB_TOKEN: "${{ steps.app-token.outputs.token }}"
+  #         header: ".#top.${{ matrix.host }}"
+  #         message: |
+  #           ### Report for `${{ matrix.host }}`
 
-            <summary> Version changes </summary> <br>
-            <pre> ${{ steps.diff.outputs.diff }} </pre>
+  #           <summary> Version changes </summary> <br>
+  #           <pre> ${{ steps.diff.outputs.diff }} </pre>
 
-  delete-runner:
-    name: Delete Hetzner Cloud runner
-    needs:
-      - create-runner
-      - nix-build
-    runs-on: ubuntu-latest
-    if: ${{ always() }} # required to stop the runner even if the error happened in the previous jobs
-    steps:
-      - name: Delete runner
-        uses: Cyclenerd/hcloud-github-runner@v1
-        with:
-          mode: delete
-          github_token: ${{ secrets.GH_PAT }}
-          hcloud_token: ${{ secrets.HETZNER_TOKEN }}
-          name: ${{ needs.create-runner.outputs.label }}
-          server_id: ${{ needs.create-runner.outputs.server_id }}
-
-  nix-build-success:
-    if: ${{ always() }}
-    needs:
-      - nix-build
-    name: Nix Build Successful
-    runs-on: ubuntu-latest
-    steps:
-      - if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}
-        name: Check matrix status
-        run: exit 1
+  # nix-build-success:
+  #   if: ${{ always() }}
+  #   needs:
+  #     - nix-build
+  #   name: Nix Build Successful
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}
+  #       name: Check matrix status
+  #       run: exit 1
